name: game_engine
description: "A super simple game engine on top of Flutter canvas"
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_sprite: #^3.0.5
    path: ../flutter_sprite
  collection: ^1.14.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
